name = "clinic-feedback-wrangler"
compatibility_date = "2025-11-01"

[assets]
directory = "."

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
